spring:
  main:
    banner-mode: "off"
    log-startup-info: false
  application:
    name: coderdojo
  config:
    import: "optional:file:.env[.properties]"
  shell:
    interactive:
      enabled: true
logging:
  level:
    root: info
    be.coderdojo.ninove: info
    org.springframework.boot: error
    org.springframework.shell: error

eventbrite:
  api:
    token: ${EVENTBRITE_API_TOKEN:placeholder}
    base-url: https://www.eventbriteapi.com/v3
    organization-id: ${EVENTBRITE_ORG_ID:placeholder}
